on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update
        run: sudo apt-get update

      - name: Install gcc
        run: sudo apt-get install -y gcc

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build
        run: make
